- name: Deploy Flask App to Web Servers
  hosts: webservers
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name:
          - python3
          - python3-pip
        update_cache: yes

    - name: Install Flask
      pip:
        name: flask

    - name: Create app directory
      file:
        path: /opt/flaskapp
        state: directory

    - name: Copy app.py to server
      copy:
        src: app.py
        dest: /opt/flaskapp/app.py
        mode: '0644'

    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/flaskapp.service
        content: |
          [Unit]
          Description=Flask App
          After=network.target

          [Service]
          ExecStart=/usr/bin/python3 /opt/flaskapp/app.py
          WorkingDirectory=/opt/flaskapp
          Restart=always
          User=ubuntu

          [Install]
          WantedBy=multi-user.target

    - name: Start Flask app
      systemd:
        name: flaskapp
        state: started
        enabled: true

- name: Set Up HAProxy Load Balancer
  hosts: HAproxy
  become: true
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        update_cache: yes

    - name: Generate HAProxy config
      copy:
        dest: /etc/haproxy/haproxy.cfg
        content: |
          global
              log /dev/log local0
              log /dev/log local1 notice
              daemon

          defaults
              log     global
              mode    http
              option  httplog
              timeout connect 5000
              timeout client  50000
              timeout server  50000

          frontend http_front
              bind *:80
              default_backend http_back

          backend http_back
              balance roundrobin
              option httpchk GET /
              server devA 10.0.1.11:5000 check
              server devB 10.0.1.12:5000 check
              server devC 10.0.1.13:5000 check

    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted
        enabled: true