- name: Create a application with load balencer
  hosts: all
  become: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

- name: Create servers dev(A,B,C)
  hosts: webservers
  become: true

  tasks:
    - name: Install python packages
      apt:
        name: ['python3', 'python3-pip', 'python3-flask', 'snmpd']
        state: present
        update_cache: yes

    - name: Create application directory 
      file:
        path: /opt/flaskapp
        state: directory
        mode: '0755'

    - name: Configure application
      copy:
        src: application2.py
        dest: /opt/flaskapp/application2.py
        mode: '0644'

    - name: Create application service
      copy:
        src: flaskapp.service
        dest: /etc/systemd/system/flaskapp.service
        mode: '0644'

    - name: Start application
      systemd:
        daemon_reload: yes
        name: flaskapp
        state: restarted
        enabled: yes

    - name: Configure SNMPd to listen on UDP 6000 on all interfaces
      lineinfile:
        path: /etc/snmp/snmpd.conf
        regexp: '^agentaddress\s+.*'
        line: 'agentaddress udp:6000'
      notify: Restart SNMPd

    - name: Ensure snmpd is started and enabled
      systemd:
        name: snmpd
        state: started
        enabled: yes

  handlers:
    - name: Restart SNMPd
      systemd:
        name: snmpd
        state: restarted

- name: Configure haproxy loadbalencer
  hosts: HAproxy
  become: true

  tasks:
    - name: Install haproxy loadbalencer
      apt:
        name: ['haproxy', 'nginx']
        state: present
        update_cache: yes

    - name: Configuring haproxy loadbalencer
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
      notify: Restart haproxy server

    - name: Enable haproxy service to start on boot
      service:
        name: haproxy
        state: restarted
        enabled: yes
        daemon_reload: yes

    - name: Configure NGINX UDP
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
        force: yes
      notify: Reload NGINX

    - name: Ensure NGINX is running
      systemd:
        name: nginx
        state: started
        enabled: yes
        daemon_reload: yes

  handlers:
    - name: Restart haproxy server
      service:
        name: haproxy
        state: restarted

    - name: Reload NGINX
      systemd:
        name: nginx
        state: reloaded