---
- name: Create application with load balancer
  hosts: all
  become: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

- name: Create servers dev(A,B,C)
  hosts: webservers
  become: true

  tasks:
    - name: Install python packages and snmpd
      apt:
        name:
          - python3
          - python3-pip
          - python3-flask
          - snmpd
        state: present
        update_cache: yes

    - name: Create application directory
      file:
        path: /opt/flaskapp
        state: directory
        mode: '0755'

    - name: Configure application
      copy:
        src: application2.py
        dest: /opt/flaskapp/application2.py
        mode: '0644'

    - name: Create application service
      copy:
        src: flaskapp.service
        dest: /etc/systemd/system/flaskapp.service
        mode: '0644'

    - name: Start application
      systemd:
        daemon_reload: yes
        name: flaskapp
        state: restarted
        enabled: yes

    - name: Configure SNMPd to listen on UDP 161 on all interfaces
      lineinfile:
        path: /etc/snmp/snmpd.conf
        regexp: '^agentaddress\s+.*'
        line: 'agentaddress udp:161'
      notify: Restart SNMPd

    - name: Ensure snmpd is started and enabled
      systemd:
        name: snmpd
        state: started
        enabled: yes

  handlers:
    - name: Restart SNMPd
      systemd:
        name: snmpd
        state: restarted
        enabled: yes
        daemon_reload: yes

- name: Configure HAproxy and NGINX for load balancing
  hosts: HAproxy
  become: true

  tasks:
    - name: Install HAproxy and NGINX
      apt:
        name:
          - haproxy
          - nginx
        state: present
        update_cache: yes

    - name: Configure HAproxy for Flask app
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
      notify: Validate and Restart HAproxy

    - name: Configure NGINX for SNMP UDP proxy
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
        force: yes
      notify: Reload NGINX

    - name: Ensure default HTTP site is removed
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Remove default HTTP site config file
      file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Ensure NGINX is running
      systemd:
        name: nginx
        state: started
        enabled: yes
        daemon_reload: yes

  handlers:
    - name: Validate and Restart HAproxy
      block:
        - name: Validate HAproxy configuration
          command: haproxy -c -f /etc/haproxy/haproxy.cfg
          register: haproxy_check
          changed_when: false
          failed_when: haproxy_check.rc != 0

        - name: Stop HAproxy service before restart
          systemd:
            name: haproxy
            state: stopped

        - name: Restart HAproxy service
          systemd:
            name: haproxy
            state: started
            enabled: yes
            daemon_reload: yes

        - name: Show HAproxy config validation output
          debug:
            var: haproxy_check.stdout_lines

    - name: Reload NGINX
      systemd:
        name: nginx
        state: reloaded
        enabled: yes
        daemon_reload: yes
