- name: Create a application with load balencer
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

- name: Create servers dev(A,B,C)
  hosts: webservers
  become: true

  tasks:
    - name: Install python packages
      apt:
        name: ['python3', 'python3-pip', 'python3-flask']
        state: present

    - name: Create application directory 
      file:
        path: /opt/flaskapp
        state: directory
        mode: '0755'

    - name: Create application
      copy:
        src: application2.py
        dest: /opt/flaskapp/application2.py
        mode: '0644'

    - name: Install application
      pip:
        name: flask
        executable: pip3

    - name: Create application service
      copy:
        src: flaskapp.service
        dest: /etc/systemd/system/flaskapp.service
        mode: '0644'

    - name: Start application
      systemd:
        name: flaskapp
        enabled: yes
        state: started
        daemon_reload: yes

- name: Configure haproxy loadbalencer
  hosts: HAproxy
  become: true

  tasks:
    - name: Install haproxy loadbalencer
      apt:
        name: haproxy
        state: present

    - name: Configuring haproxy loadbalencer
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
      notify: Restart haproxy server

    - name: Enable haproxy service to start on boot
      service:
        name: haproxy
        enabled: yes

  handlers:
    - name: Restart haproxy server
      service:
        name: haproxy
        state: restarted