- name: Create an application with load balencer
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

- name: Create servers dev(A,B,C)
  hosts: webservers
  become: true

  tasks:
    - name: Install python packages
      apt:
        name: ['python3', 'python3-pip', 'python3-flask','snmpd']
        state: present

    - name: Create application directory 
      file:
        path: /opt/flaskapp
        state: directory
        mode: '0755'

    - name: Create application
      copy:
        src: application2.py
        dest: /opt/flaskapp/application2.py
        mode: '0644'

    - name: Create application service
      copy:
        src: flaskapp.service
        dest: /etc/systemd/system/flaskapp.service
        mode: '0644'

    - name: Start application
      systemd:
        name: flaskapp
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Ensure SNMPd config exists
      file:
        path: /etc/snmp/snmpd.conf
        state: touch
        mode: '0644'
    - name: Configure SNMPd to listen on UDP 161
      lineinfile:
        path: /etc/snmp/snmpd.conf
        regexp: '^agentAddress\s+.*'
        line: 'agentAddress udp:161'
      notify: Restart SNMPd

    - name: Ensure snmpd is started and enabled
      systemd:
        name: snmpd
        state: started
        enabled: yes

  handlers:
    - name: Restart SNMPd
      systemd:
        name: snmpd
        state: restarted

# ------------------------------------------------------
- name: Configure HAProxy on proxy host
  hosts: HAproxy
  become: true
  tasks:
    - name: Install HAProxy and NGINX
      apt: 
        name: 
          - haproxy
          - nginx
        state: present
        update_cache: yes

    - name: Configure HAProxy config
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
      notify: Restart HAProxy

    - name: Check HAProxy configuration syntax
      command: haproxy -c -f /etc/haproxy/haproxy.cfg
      register: haproxy_check
      ignore_errors: yes

    - name: Fail if HAProxy config syntax check failed
      fail:
        msg: "HAProxy config syntax error:\n{{ haproxy_check.stderr }}"
      when: haproxy_check.rc != 0

    - name: Enable & start HAProxy
      systemd:
        name: haproxy
        enabled: yes
        state: started
        daemon_reload: yes
    - name: Configure NGINX UDP
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
        force: yes
      notify: Reload NGINX

    - name: Ensure NGINX is running
      systemd:
        name: nginx
        state: started
        enabled: yes
        daemon_reload: yes

  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted
        daemon_reload: yes

    - name: Reload NGINX
      systemd:
        name: nginx
        state: reloaded